ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('shop/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='ShopHome'),
    path('about/', views.about, name='AboutUs'),
    path('contact/', views.contact, name='ContactUs'),
    path('tracker/', views.tracker, name='TrackingStatus'),
    path('search/', views.search, name='Search'),
    path('productview/<int:prod_id>', views.prodview, name='ProductView'),
    path('checkout/', views.checkout, name='Checkout'),
]

shop/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    desc = models.CharField(max_length=300)
    pub_data = models.DateField()
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to="shop/images", default="")

    def __str__(self):
        return self.product_name


class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, default="")
    email = models.EmailField(default="")
    phone = models.CharField(max_length=15, default="")
    desc = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.email


class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=200)
    amount = models.IntegerField()
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    addressline = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=50)

    def __str__(self):
        return self.name +" Order ID: "+str(self.order_id)


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=200)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:10] + "..."

shop/views.py
from django.shortcuts import render
from .models import Product, Contact, Order, OrderUpdate
from math import ceil
import json
from django.http import HttpResponse


# Create your views here.
def index(request):
    all_products = []
    product_category = Product.objects.values('category', 'id')
    category = {item['category'] for item in product_category}
    for cat in category:
        prod = Product.objects.filter(category=cat)
        n = len(prod)
        no_of_slides = n // 4 + ceil((n / 4) - (n // 4))
        all_products.append([prod, range(1, no_of_slides), no_of_slides])
    context = {'all_products': all_products, 'title': 'My~E-Commerce'}
    return render(request, 'shop/index.html', context)


def search_match(query, item):
    if query in item.desc.lower() or query in item.product_name.lower() or query in item.category.lower():
        return True
    else:
        return False


def search(request):
    query = request.GET.get('search')
    all_products = []
    product_category = Product.objects.values('category', 'id')
    category = {item['category'] for item in product_category}
    for cat in category:
        prod = Product.objects.filter(category=cat)
        product = [item for item in prod if search_match(query, item)]
        n = len(product)
        no_of_slides = n // 4 + ceil((n / 4) - (n // 4))
        if len(product) != 0:
            all_products.append([product, range(1, no_of_slides), no_of_slides])
    context = {'all_products': all_products, 'msg': ""}
    if len(all_products) == 0 or len(query) < 3:
        context = {'msg': "Please make sure to enter relevant search"}
    return render(request, 'shop/search.html', context)


def about(request):
    return render(request, 'shop/aboutus.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
    return render(request, 'shop/contact.html')


def tracker(request):
    if request.method=="POST":
        orderId = request.POST.get('orderId', '')
        email = request.POST.get('email', '')
        try:
            order = Order.objects.filter(order_id=orderId, email=email)
            if len(order)>0:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                for item in update:
                    updates.append({'text': item.update_desc, 'time': item.timestamp})
                    response = json.dumps({"status":"success", "updates": updates,
                     "itemsJson": order[0].items_json}, default=str)
                return HttpResponse(response)
            else:
                return HttpResponse('{"status":"noitem"}')
        except Exception as e:
            return HttpResponse('{"status":"error"}')

    return render(request, 'shop/tracker.html')


def prodview(request, prod_id):
    # Fetch the product using id
    product = Product.objects.filter(id=prod_id)
    return render(request, 'shop/productview.html', {'products': product[0]})


def checkout(request):
    if request.method == 'POST':
        items_json = request.POST.get('itemsJson', '')
        amount = request.POST.get('amount')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        address = request.POST.get('address', '')
        addressline = request.POST.get('addressline', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        order = Order(items_json=items_json, amount=amount, name=name, email=email, phone=phone,
                      address=address, addressline=addressline,
                      city=city, state=state, zip_code=zip_code)
        order.save()
        update = OrderUpdate(order_id=order.order_id, update_desc="Order has been placed")
        update.save()
        confirm_order = True
        id = order.order_id
        return render(request, 'shop/checkout.html', {'confirm_order': confirm_order, 'id': id})
    return render(request, 'shop/checkout.html')

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'shop:ShopHome' %}">E-Commerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:ShopHome' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:AboutUs' %}">About Us</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:TrackingStatus' %}">Tracker</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:ContactUs' %}">Contact Us</a>
      </li>
    </ul>
    <form method="get" action="{% url 'shop:Search' %}" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" id="search" name="search"
             placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
      <button type="button" class="btn btn-secondary mx-2" data-container="body" id="popcart"
              data-toggle="popover" data-placement="bottom" data-html="true">
                Cart(<span id="cart">0</span>)
    </button>
  </div>
</nav>
{% block css %}{% endblock css %}
{% block content %}{% endblock content %}
{% block js %}
    <script>
    // Find out the cart items from localStorage
    if (localStorage.getItem('cart') == null) {
        var cart = {};
    } else {
        cart = JSON.parse(localStorage.getItem('cart'));
        updateCart(cart);
    }
    // If the add to cart button is clicked, add/increment the item
    //$('.cart').click(function() {
        $('.divpr').on('click', 'button.cart', function(){
        var idstr = this.id.toString();
        if (cart[idstr] != undefined) {
            qty = cart[idstr][0]+1;
        } else {
            qty = 1;
            var name = document.getElementById('name'+idstr).innerHTML;
            var price = document.getElementById('price'+idstr).innerHTML;
            cart[idstr] = [qty, name, parseFloat(price)];
        }
        updateCart(cart);
    });
    //Add Popover to cart
    $('#popcart').popover('show');
    updatePopover(cart);
    function updatePopover(cart) {
        var popStr = "";
        popStr = popStr + "<h5> Items in Your Shopping Cart </h5><div class='mx-2 my-2'>";
        var i = 1;
        for (var item in cart) {
            popStr = popStr + "<b>" + i + "</b>. ";
            popStr = popStr + document.getElementById('name' + item).innerHTML.slice(0, 19) +
                "... Qty: " + cart[item][0] + '<br>';
            i = i + 1;
        }
        popStr = popStr + "</div><a href='{% url "shop:Checkout" %}' class='btn btn-primary' id='checkout'>Checkout</a>" +
            "<a href='#' onclick='clearCart()' class='btn btn-primary ml-2' id='clearCart'>Clear Cart</a>"
        document.getElementById('popcart').setAttribute('data-content', popStr);
        $('#popcart').popover('show');
    }
    function clearCart() {
        cart = JSON.parse(localStorage.getItem('cart'));
        for (var item in cart) {
            document.getElementById('div' + item).innerHTML = '<button id="' + item +
                '" class="btn btn-primary cart">Add To Cart</button>'
        }
        localStorage.clear();
        cart = {};
        updateCart(cart);
    }
    function updateCart(cart) {
        var sum = 0;
        for (var item in cart) {
            sum = sum + cart[item][0];
            document.getElementById('div' + item).innerHTML = "<button id='minus" + item +
                "' class='btn btn-primary minus'>-</button> <span id='val" + item + "''>" +
                cart[item][0] + "</span> <button id='plus" + item +
                "' class='btn btn-primary plus'> + </button>";
        }
        localStorage.setItem('cart', JSON.stringify(cart));
        document.getElementById('cart').innerHTML = sum;
        console.log(cart);
        updatePopover(cart);
    }
    // If plus or minus button is clicked, change the cart as well as the display value
    $('.divpr').on("click", "button.minus", function() {
        a = this.id.slice(7, );
        cart['pr' + a][0] = cart['pr' + a][0] - 1;
        cart['pr' + a][0] = Math.max(0, cart['pr' + a][0]);
        document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
        updateCart(cart);
    });
    $('.divpr').on("click", "button.plus", function() {
        a = this.id.slice(6, );
        cart['pr' + a][0] = cart['pr' + a][0] + 1;
        document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
        updateCart(cart);
    });
    </script>
{% endblock js %}
</body>
</html>

templates/shop/aboutus.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">My E-Commerce Awesome Cart</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>
{% endblock content %}

templates/shop/checkout.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
    <div class="col my-4">
        <h2>Step 1 - My E-Commerce Cart Express Checkout- Review Your Cart Item</h2>
        <div id="items">
            <ul class="list-group" id="items"></ul>
        </div>
        <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active font-weight-bold"
                        aria-current="page">Your Total Price is : Rs
                        <span id="totalPrice"></span> /- Thank you for using My~E-Commerce
                    </li>
                </ol>
        </nav>
    </div>

    <div class="col my-4">
        <h2>Step 2 - Enter Address & Other Details :</h2>
        <form method="post" action="{% url 'shop:Checkout' %}">{% csrf_token %}
            <input type="hidden" name="itemsJson" id="itemJson">
            <input type="hidden" name="amount" id="amount">
          <div class="form-row">
              <div class="form-group col-md-6">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group col-md-4">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
              <div class="form-group col-md-2">
              <label for="phone">Phone</label>
              <input type="number" class="form-control" id="phone" name="phone"
                     placeholder="98....">
            </div>
          </div>
          <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address"
                   placeholder="1234 Main St">
          </div>
          <div class="form-group">
            <label for="addressline">Address Line 2</label>
            <input type="text" class="form-control" id="addressline" name="addressline"
                   placeholder="Apartment, studio, or floor">
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="city">City</label>
              <input type="text" class="form-control"  name="city" id="city">
            </div>
            <div class="form-group col-md-4">
              <label for="state">State</label>
              <input type="text" class="form-control" name="state" id="state">
            </div>
            <div class="form-group col-md-2">
              <label for="zip_code">Zip</label>
              <input type="text" class="form-control" name="zip_code" id="zip_code">
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
    </div>
{% endblock content %}
{% block js %}
    <script>
    var sum = 0;
    var totalPrice=0;
        if (localStorage.getItem('cart') == null) {
        var cart = {};
    } else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    if ($.isEmptyObject(cart)){
        mystr = `<p class="text-info text-center">Your Shopping cart is empty please add
            some item to you cart before checking out</p>`
        $('#items').append(mystr)
    }else {
        for (item in cart){
            let name = cart[item][1];
            let qty = cart[item][0];
            let itemPrice =cart[item][2]
            mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                ${name}
                <span class="badge badge-primary badge-pill">${qty}</span>
              </li>`
            $('#items').append(mystr);
            sum = sum + qty
            totalPrice = totalPrice+qty*itemPrice
        }
    }
        document.getElementById('cart').innerHTML = sum;
        document.getElementById('totalPrice').innerHTML = totalPrice;
    $('#itemJson').val(JSON.stringify(cart));
    {% if confirm_order %}
        alert('Thank for ordering with us. Your order id is {{ id }}. Use it to track your order')
        localStorage.clear();
        document.location='/shop/';
    {% endif %}
    $('#amount').val($('#totalPrice').html())
    </script>
{% endblock js %}

templates/shop/contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container my-3">
    <div class="row">
        <div class="offset-2"></div>
        <div class="col-8">
            <h3>Contact Us</h3>
                <form action="{% url 'shop:ContactUs' %}" method="post">{% csrf_token %}
                <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name='name' placeholder="Enter Your Name">
              </div>
              <div class="form-group">
                <label for="name">Email</label>
                <input type="email" class="form-control" id="email" name='email' placeholder="Enter Your Email">
              </div>
                    <div class="form-group">
                    <label for="name">Phone</label>
                    <input type="tel" class="form-control" id="phone" name='phone' placeholder="Enter Your Phone Number">
                    </div>
                   <div class="form-group">
                    <label for="desc">How May We Help You?</label>
                    <textarea class="form-control" id="desc" name='desc' rows="3"></textarea>
                  </div>
                    <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
        <div class="offset-2"></div>
    </div>
    </div>
{% endblock content %}

templates/shop/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block css %}
    <style>
          .col-md-3 {
          display: inline-block;
          }
          .carousel-indicators .active {
             background-color: blue;
            }
          .carousel-control-prev,
          .carousel-control-next{
              top: auto;
              bottom: auto;
              padding-top: 222px;
          }
    </style>
{% endblock css %}
{% block content %}
    <div class="container">
    <!--Slideshow starts here -->
    {% for product, range, no_of_slides in all_products %}
    <h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
    <div class="row">
<div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active bg-primary"></li>
       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" class="bg-primary" ></li>
      {% endfor %}
    </ul>
    <div class="container carousel-inner no-padding">
      <div class="carousel-item active">
        {% for i in product %}
        <div class="col-xs-3 col-sm-3 col-md-3 mr-5">
          <div class="card" style="width: 18rem; height: 25rem">
            <img src='/media/{{i.image}}' class="card-img-top" alt="{{i.product_name}}">
            <div class="card-body">
              <h5 class="card-title" id="namepr{{ i.id }}">{{i.product_name}}</h5>
              <p class="card-text">{{i.desc|slice:"0:50"}}...</p>
                <h6 class="card-title">Price:<span id="pricepr{{ i.id }}">{{ i.price }}</span> /-</h6>
                <span id="divpr{{ i.id }}" class="divpr">
                    <div class="mt-3">
                    <button id="pr{{i.id}}" class="btn btn-primary cart">Add To Cart</button>
                    <a href="{% url 'shop:ProductView' i.id %}"><button id="qv{{i.id}}"
                    class="btn btn-primary cart">Quick View</button></a>
                </div></span>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}
        {% endfor %}
    </div>
</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon bg-primary"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon bg-primary"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock content%}

templates/shop/productview.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="container my-4">
    <div class="row">
            <div class="col-md-4">
                <div class="row">
                 <img src="/media/{{ products.image }}" alt="{{ products.product_name }}"
                      width="233px" height="385px">
                </div>
                <div class="row mt-2">
                    <button class="btn btn-primary mx-3">Buy Now</button>
                    <button class="btn btn-primary">Add To Cart</button>
                </div>
            </div>
        <div class="col-md-8">
            <h5>{{ products.product_name }}</h5>
            <p class="font-weight-bold">Rs. {{ products.price }} /-</p>
            <p>{{ products.desc }}</p>
        </div>
    </div>
    </div>
{% endblock content %}

templates/shop/search.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block css %}
    <style>
          .col-md-3 {
          display: inline-block;
          }
          .carousel-indicators .active {
             background-color: blue;
            }
          .carousel-control-prev,
          .carousel-control-next{
              top: auto;
              bottom: auto;
              padding-top: 222px;
          }
    </style>
{% endblock css %}
{% block content %}
    <div class="container">
    <!--Slideshow starts here -->
    {% for product, range, no_of_slides in all_products %}
    <h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
    <div class="row">
<div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active bg-primary"></li>
       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" class="bg-primary" ></li>
      {% endfor %}
    </ul>
    <div class="container carousel-inner no-padding">
      <div class="carousel-item active">
        {% for i in product %}
        <div class="col-xs-3 col-sm-3 col-md-3 mr-5">
          <div class="card" style="width: 18rem; height: 25rem">
            <img src='/media/{{i.image}}' class="card-img-top" alt="{{i.product_name}}">
            <div class="card-body">
              <h5 class="card-title" id="namepr{{ i.id }}">{{i.product_name}}</h5>
              <p class="card-text">{{i.desc|slice:"0:50"}}...</p>
                <h6 class="card-title">Price:<span id="pricepr{{ i.id }}">{{ i.price }}</span> /-</h6>
                <span id="divpr{{ i.id }}" class="divpr">
                    <div class="mt-3">
                    <button id="pr{{i.id}}" class="btn btn-primary cart">Add To Cart</button>
                    <a href="{% url 'shop:ProductView' i.id %}"><button id="qv{{i.id}}"
                    class="btn btn-primary cart">Quick View</button></a>
                </div></span>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}
        {% endfor %}
    </div>
</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon bg-primary"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon bg-primary"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock content%}
{% block js %}
    <script>
        {% if msg|length != 0 %}
                alert('{{ msg }}')
            window.location.href = "/"
        {% endif %}
    </script>
{% endblock %}

templates/shop/tracker.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
    <div class="col my-4">
        <h2>Enter your Order Id and Email address to track your order</h2>
        <form method="post" action="#" id="trackerForm">{% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputname">Order Id</label>
                    <input type="text" class="form-control" id="orderId" name="orderId" placeholder="Order Id">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                </div>
                <button type="submit" class="btn btn-primary">Track Order</button>
            </div>
    </div>
    <div class="col my-4">
        <h2>Your Order Status</h2>
        <div class="my-4">
            <ul class="list-group" id="items">
                Enter your order Id and Email and click Track Order to find details about your order!
            </ul>
        </div>
        <h2>Your Order Details</h2>
        <div class="my-4">
            <ul class="list-group" id="citems">
            </ul>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
    <script>
$('#trackerForm').submit(function(event) {
    $('#items').empty();
    var formData = {
        'orderId': $('input[name=orderId]').val(),
        'email': $('input[name=email]').val(),
        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
    };
    $.ajax({
            type: 'POST',
            url: '/shop/tracker/',
            data: formData,
            encode: true
        })
        .done(function(data) {
            $('#citems').empty();
            data = JSON.parse(data);
            if (data['status'] == 'success') {
                updates = data['updates'];
                for (i = 0; i < updates.length; i++) {
                    let text = updates[i]['text'];
                    let time = updates[i]['time'];
                    mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${text}
                    <span class="badge badge-primary badge-pill">${time}</span>
                </li>`
                    $('#items').append(mystr);
                }
                // Fill in the order details
                cart = JSON.parse(data['itemsJson']);
                for (item in cart) {
                    let name = cart[item][1];
                    let qty = cart[item][0];
                    mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                    <span class="badge badge-primary badge-pill">${qty}</span>
                </li>`
                    $('#citems').append(mystr);
                }
            } else {
                mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    Sorry, We are not able to fetch this order id and email. Make sure to type correct order Id and email</li>`
                $('#items').append(mystr);
                $('#citems').append(mystr);
            }
        });
    event.preventDefault();
});
</script>
{% endblock js %}